version: "3"

networks:
  public-net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/24
          gateway: 10.100.0.10
        - subnet: 2001:db8:3200::/64
          gateway: 2001:db8:3200::10
  site-1:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.10
        - subnet: 2001:db8:3210::/64
          gateway: 2001:db8:3210::1000
  site-2:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/24
          gateway: 10.20.0.10
        - subnet: 2001:db8:3220::/64
          gateway: 2001:db8:3220::1000
  site-3:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.0.0/24
          gateway: 10.30.0.10
        - subnet: 2001:db8:3230::/64
          gateway: 2001:db8:3230::1000

services:
  site-1:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.100.0.1
        ipv6_address: 2001:db8:3200::1
      site-1:
        ipv4_address: 10.10.0.1
        ipv6_address: 2001:db8:3210::1
    hostname: site-1
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.primary-endpoint=10.100.0.1
      - --bootstrap.enabled
      - --raft.in-memory
      - --app-daemon
      - --app-daemon-bind=0.0.0.0:8081
      - --plugins.debug.listen-address=:6061
      - --plugins.debug.enable-db-querier=true
    ports:
      - 8081:8081
      - 6061:6061
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  site-2:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.100.0.2
        ipv6_address: 2001:db8:3200::2
      site-2:
        ipv4_address: 10.20.0.1
        ipv6_address: 2001:db8:3220::1
    hostname: site-2
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.primary-endpoint=10.100.0.2
      - --bootstrap.enabled
      - --raft.in-memory
      - --app-daemon
      - --app-daemon-bind=0.0.0.0:8082
      - --plugins.debug.listen-address=:6062
      - --plugins.debug.enable-db-querier=true
    ports:
      - 8082:8082
      - 6062:6062
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  site-3:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.100.0.3
        ipv6_address: 2001:db8:3200::3
      site-3:
        ipv4_address: 10.30.0.1
        ipv6_address: 2001:db8:3230::1
    hostname: site-3
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.primary-endpoint=10.100.0.3
      - --bootstrap.enabled
      - --raft.in-memory
      - --app-daemon
      - --app-daemon-bind=0.0.0.0:8083
      - --plugins.debug.listen-address=:6063
      - --plugins.debug.enable-db-querier=true
    ports:
      - 8083:8083
      - 6063:6063
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
