version: "3"

networks:
  public-net:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
          gateway: 10.1.0.100
  site-1:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
  site-2:
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/24
  site-3:
    ipam:
      driver: default
      config:
        - subnet: 10.30.0.0/24

services:
  turn-server:
    image: ghcr.io/webmeshproj/turn:latest
    networks:
      public-net:
        ipv4_address: 10.1.0.1
    entrypoint:
      - /webmesh-turn
      - --public-ip=10.1.0.1
      - --enable-campfire=true
    restart: on-failure

  site-1:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.1.0.2
      site-1:
    hostname: site-1
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --global.no-ipv6
      - --bootstrap.enabled
      - --raft.in-memory
      - --mesh.join-as-voter
      - --services.api.webrtc
      - --services.api.stun-servers=stun:10.1.0.1:3478
      - --app-daemon
      - --app-daemon-bind=0.0.0.0:8081
    ports:
      - 8081:8081
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-2:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.1.0.3
      site-2:
    hostname: site-2
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --global.no-ipv6
      - --bootstrap.enabled
      - --raft.in-memory
      - --mesh.join-as-voter
      - --services.api.webrtc
      - --services.api.stun-servers=stun:10.1.0.1:3478
      - --app-daemon
      - --app-daemon-bind=0.0.0.0:8082
    ports:
      - 8082:8082
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-3:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.1.0.4
      site-3:
    hostname: site-3
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --global.no-ipv6
      - --bootstrap.enabled
      - --raft.in-memory
      - --mesh.join-as-voter
      - --services.api.webrtc
      - --services.api.stun-servers=stun:10.1.0.1:3478
      - --app-daemon
      - --app-daemon-bind=0.0.0.0:8083
    ports:
      - 8083:8083
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
