version: '3'

services:
  bootstrap-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    network_mode: host
    hostname: bootstrap-node
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --global.log-level=debug
      - --global.primary-endpoint=192.168.100.165
      - --bootstrap.enabled
      - --bootstrap.default-network-policy=accept
      - --bootstrap.ipv4-network=10.10.10.0/24
    ports:
      - 8443:8443
      - 51820:51820/udp
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

