version: "3"

networks:
  public-net:
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/24
          gateway: 10.100.0.10
  site-1:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
  site-2:
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/24
  site-3:
    ipam:
      driver: default
      config:
        - subnet: 10.30.0.0/24

services:
  site-1:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.100.0.1
      site-1:
    hostname: site-1
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.primary-endpoint=10.100.0.1
      - --global.no-ipv6
      - --global.log-level=debug
      - --bootstrap.enabled
      - --raft.in-memory
      - --app-daemon
      - --app-daemon-bind=0.0.0.0:8081
      - --plugins.debug.listen-address=:6060
      - --plugins.debug.enable-db-querier=true
    ports:
      - 8081:8081
      - 6060:6060
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-2:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.100.0.2
      site-2:
    hostname: site-2
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.primary-endpoint=10.100.0.2
      - --global.no-ipv6
      - --global.log-level=debug
      - --bootstrap.enabled
      - --raft.in-memory
      - --app-daemon
      - --app-daemon-bind=0.0.0.0:8082
    ports:
      - 8082:8082
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-3:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.100.0.3
      site-3:
    hostname: site-3
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.primary-endpoint=10.100.0.3
      - --global.no-ipv6
      - --bootstrap.enabled
      - --raft.in-memory
      - --app-daemon
      - --app-daemon-bind=0.0.0.0:8083
    ports:
      - 8083:8083
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
